ALTER TABLE t_collateral  ADD INDEX IDX_T_COLLATERAL_LOAN_ID (`LOAN_ID`); 
ALTER TABLE t_judge_adv   ADD INDEX IDX_T_JUDGE_ADV_LOAN_ID  (`LOAN_ID`);
ALTER TABLE t_loan_app    ADD INDEX IDX_T_LOAN_APP_LOAN_ID   (`LOAN_ID`);
ALTER TABLE t_loan_base   ADD INDEX IDX_T_LOAN_BASE_LOAN_ID  (`LOAN_ID`);
ALTER TABLE t_loan_guar   ADD INDEX IDX_T_LOAN_GUAR_LOAN_ID  (`LOAN_ID`);
ALTER TABLE t_contract    ADD INDEX IDX_T_CONTRACT_LOAN_ID   (`LOAN_ID`);

ALTER TABLE t_collateral_price_audit ADD INDEX IDX_T_COLLATERAL_PRICE_AUDIT_COLLATERAL_ID (`COLLATERAL_ID`);

ALTER TABLE t_bpm_log   ADD INDEX IDX_T_BPM_LOG_BIZ_KEY  (`BIZ_KEY`);
ALTER TABLE t_bpm_task  ADD INDEX IDX_T_BPM_TASK_BIZ_KEY (`BIZ_KEY`);

ALTER TABLE t_data_dictionary ADD INDEX IDX_T_DATA_DICT_KEY_NAME (`KEY_NAME`);
ALTER TABLE t_data_dictionary ADD INDEX IDX_T_DATA_DICT_PARENT_KEY_PROP (`PARENT_KEY_PROP`);

ALTER TABLE T_BILL_ACCT   ADD INDEX IDX_T_BILL_ACCT_LOAN_ID  (`LOAN_ID`);
ALTER TABLE T_BILL_ONLIINE   ADD INDEX IDX_T_BILL_ONLIINE_LOAN_ID  (`LOAN_ID`);
ALTER TABLE T_BILL_BASE    ADD INDEX IDX_T_BILL_BASE_LOAN_ID   (`LOAN_ID`);