/************************************** oracle 创建序列   **********************************/
create sequence T_ACCT_APP_SEQ increment by 1 start with 1; 
create sequence T_ARCHIVE_INFO_SEQ increment by 1 start with 1;
create sequence T_BULLETIN_SEQ increment by 1 start with 1;
create sequence T_BILL_ACCT_SEQ increment by 1 start with 1; 
create sequence T_BILL_BASE_SEQ increment by 1 start with 1; 
create sequence T_BILL_ONLINE_SEQ increment by 1 start with 1; 
create sequence T_BPM_LOG_SEQ increment by 1 start with 1; 
create sequence T_BPM_TASK_SEQ increment by 1 start with 1; 
create sequence T_CLLT_DISTR_SEQ increment by 1 start with 1; 
create sequence T_CLLT_LOG_SEQ increment by 1 start with 1; 
create sequence T_COLLATERAL_SEQ increment by 1 start with 1; 
create sequence T_COLLATERAL_CHECK_SEQ increment by 1 start with 1; 
create sequence T_COLLATERAL_PRICE_AUDIT_SEQ increment by 1 start with 1; 
create sequence T_COLLATERAL_PRICE_CHANGE_SEQ increment by 1 start with 1; 
create sequence T_CONTACT_SEQ increment by 1 start with 1; 
create sequence T_CONTRACT_SEQ increment by 1 start with 1; 
create sequence T_CONTRACT_ONLINE_SEQ increment by 1 start with 1; 
create sequence T_FILES_SEQ increment by 1 start with 1; 
create sequence T_INTERFACE_LOG_SEQ increment by 1 start with 1; 
create sequence T_JUDGE_ADV_SEQ increment by 1 start with 1; 
create sequence T_LEND_USER_LOG_SEQ increment by 1 start with 1; 
create sequence T_LOAN_APP_SEQ increment by 1 start with 1; 
create sequence T_LOAN_BASE_SEQ increment by 1 start with 1; 
create sequence T_LOAN_GUAR_SEQ increment by 1 start with 1; 
create sequence T_MARGIN_INFO_SEQ increment by 1 start with 1; 
create sequence T_ONLINE_STATES_SEQ increment by 1 start with 1; 
create sequence T_OVERDUE_ACCEPT_SEQ increment by 1 start with 1; 
create sequence T_OVERDUE_REPORT_SEQ increment by 1 start with 1; 
create sequence T_REPORT_ACCT_SEQ increment by 1 start with 1; 
create sequence T_REPORT_DEAL_SEQ increment by 1 start with 1; 
create sequence T_REPORT_OVERDUE_SEQ increment by 1 start with 1; 
create sequence T_RET_PLAN_SEQ increment by 1 start with 1; 
create sequence T_SALES_CHECK_LOG_SEQ increment by 1 start with 1;  
create sequence T_SYSLOG_SEQ increment by 1 start with 1;
create sequence T_PROJECT_DETAIL_SEQ increment by 1 start with 1;  

/****以下序列中创建一次****/
create sequence T_BANK_BRANCH_INFO_SEQ increment by 1 start with 1;
create sequence T_BPM_DEF_SEQ increment by 1 start with 1; 
create sequence T_DATA_DICTIONARY_SEQ increment by 1 start with 1; 
create sequence T_DEPT_SEQ increment by 1 start with 1; 
create sequence T_LEND_USER_SEQ increment by 1 start with 1;
create sequence T_MENU_SEQ increment by 1 start with 1;
create sequence T_NODE_ORDER_SEQ increment by 1 start with 1;
create sequence T_ORG_SEQ increment by 1 start with 1; 
create sequence T_PARAMETER_SEQ increment by 1 start with 1; 
create sequence T_ROLE_SEQ increment by 1 start with 1; 
create sequence T_ROLE_MENU_REL_SEQ increment by 1 start with 1; 
create sequence T_ROLE_DATA_REL_SEQ increment by 1 start with 1;
create sequence T_USER_SEQ increment by 1 start with 1; 
create sequence T_USER_EXT_SEQ increment by 1 start with 1;
create sequence T_WAREHOUSE_SEQ increment by 1 start with 1;

/****************************************删除序列*******************************************/
drop sequence T_ACCT_APP_SEQ; 
drop sequence T_BULLETIN_SEQ;
drop sequence T_BILL_ACCT_SEQ; 
drop sequence T_BILL_BASE_SEQ; 
drop sequence T_BILL_ONLINE_SEQ; 
drop sequence T_BPM_LOG_SEQ; 
drop sequence T_BPM_TASK_SEQ; 
drop sequence T_CLLT_DISTR_SEQ; 
drop sequence T_CLLT_LOG_SEQ; 
drop sequence T_COLLATERAL_SEQ; 
drop sequence T_COLLATERAL_CHECK_SEQ; 
drop sequence T_COLLATERAL_PRICE_AUDIT_SEQ; 
drop sequence T_COLLATERAL_PRICE_CHANGE_SEQ; 
drop sequence T_CONTACT_SEQ; 
drop sequence T_CONTRACT_SEQ; 
drop sequence T_CONTRACT_ONLINE_SEQ; 
drop sequence T_FILES_SEQ; 
drop sequence T_INTERFACE_LOG_SEQ; 
drop sequence T_JUDGE_ADV_SEQ; 
drop sequence T_LEND_USER_LOG_SEQ; 
drop sequence T_LOAN_APP_SEQ; 
drop sequence T_LOAN_BASE_SEQ; 
drop sequence T_LOAN_GUAR_SEQ;  
drop sequence T_MARGIN_INFO_SEQ; 
drop sequence T_ONLINE_STATES_SEQ; 
drop sequence T_OVERDUE_ACCEPT_SEQ; 
drop sequence T_OVERDUE_REPORT_SEQ; 
drop sequence T_REPORT_ACCT_SEQ; 
drop sequence T_REPORT_DEAL_SEQ; 
drop sequence T_REPORT_OVERDUE_SEQ; 
drop sequence T_RET_PLAN_SEQ; 
drop sequence T_SALES_CHECK_LOG_SEQ;  
drop sequence T_SYSLOG_SEQ;
drop sequence T_PROJECT_DETAIL_SEQ; 
 

/******以下序列不可删除*******/ 
drop sequence T_BANK_BRANCH_INFO_SEQ; 
drop sequence T_BPM_DEF_SEQ;
drop sequence T_DATA_DICTIONARY_SEQ; 
drop sequence T_DEPT_SEQ;
drop sequence T_LEND_USER_SEQ; 
drop sequence T_MENU_SEQ; 
drop sequence T_NODE_ORDER_SEQ;
drop sequence T_ORG_SEQ; 
drop sequence T_PARAMETER_SEQ;
drop sequence T_ROLE_SEQ; 
drop sequence T_ROLE_DATA_REL_SEQ; 
drop sequence T_ROLE_MENU_REL_SEQ; 
drop sequence T_USER_SEQ; 
drop sequence T_USER_EXT_SEQ;
drop sequence T_WAREHOUSE_SEQ;