/***********************************************mysql创建序列********************************************/
insert into t_sequence values ('T_ACCT_APP_SEQ','0','1'); 
insert into t_sequence values ('T_ACCT_BILL_SEQ','0','1'); 
insert into t_sequence values ('T_BILL_AGENT_SEQ','0','1'); 
insert into t_sequence values ('T_BPM_DEF_SEQ','0','1'); 
insert into t_sequence values ('T_BPM_LOG_SEQ','0','1'); 
insert into t_sequence values ('T_BPM_TASK_SEQ','0','1'); 
insert into t_sequence values ('T_CLLT_DISTR_SEQ','0','1'); 
insert into t_sequence values ('T_CLLT_LOG_SEQ','0','1'); 
insert into t_sequence values ('T_COLLATERAL_SEQ','0','1'); 
insert into t_sequence values ('T_COLLATERAL_CHECK_SEQ','0','1'); 
insert into t_sequence values ('T_COLLATERAL_PRICE_AUDIT_SEQ','0','1'); 
insert into t_sequence values ('T_COLLATERAL_PRICE_CHANGE_SEQ','0','1'); 
insert into t_sequence values ('T_CONTACT_SEQ','0','1'); 
insert into t_sequence values ('T_CONTRACT_SEQ','0','1'); 
insert into t_sequence values ('T_DATA_DICTIONARY_SEQ','0','1'); 
insert into t_sequence values ('T_DEPT_SEQ','0','1'); 
insert into t_sequence values ('T_FILES_SEQ','0','1'); 
insert into t_sequence values ('T_JUDGE_ADV_SEQ','0','1'); 
insert into t_sequence values ('T_LEND_USER_SEQ','0','1'); 
insert into t_sequence values ('T_LEND_USER_LOG_SEQ','0','1'); 
insert into t_sequence values ('T_LOAN_APP_SEQ','0','1'); 
insert into t_sequence values ('T_LOAN_BASE_SEQ','0','1'); 
insert into t_sequence values ('T_LOAN_GUAR_SEQ','0','1'); 
insert into t_sequence values ('T_MENU_SEQ','0','1'); 
insert into t_sequence values ('T_NODE_ORDER_SEQ','0','1'); 
insert into t_sequence values ('T_ORG_SEQ','0','1'); 
insert into t_sequence values ('T_OVERDUE_ACCEPT_SEQ','0','1'); 
insert into t_sequence values ('T_OVERDUE_REPORT_SEQ','0','1'); 
insert into t_sequence values ('T_PARAMETER_SEQ','0','1'); 
insert into t_sequence values ('T_RET_PLAN_SEQ','0','1'); 
insert into t_sequence values ('T_ROLE_SEQ','0','1'); 
insert into t_sequence values ('T_ROLE_DATA_REL_SEQ','0','1');
insert into t_sequence values ('T_ROLE_MENU_REL_SEQ','0','1'); 
insert into t_sequence values ('T_SALES_CHECK_LOG_SEQ','0','1');
insert into t_sequence values ('T_SYSLOG_SEQ','0','1'); 
insert into t_sequence values ('T_USER_SEQ','0','1'); 
insert into t_sequence values ('T_USER_EXT_SEQ','0','1'); 
insert into t_sequence values ('T_WAREHOUSE_SEQ','0','1');

insert into t_sequence values ('T_LEND_USER_LOG_SEQ', '0','1');  
insert into t_sequence values ('T_BILL_ACCT_SEQ',     '0','1');  
insert into t_sequence values ('T_BILL_ONLINE_SEQ',  '0','1');  
insert into t_sequence values ('T_BILL_BASE_SEQ',     '0','1'); 
insert into t_sequence values ('T_COLLATERAL_CHECK_SEQ',     '0','1');  
insert into t_sequence values ('T_COLLATERAL_PRICE_CHANGE_SEQ',     '0','1');
insert into t_sequence values ('T_PROJECT_DETAIL_SEQ','0','1');   